# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "openshell_ocsf",
    srcs = glob(["src/**/*.rs"]),
    compile_data = glob(["schemas/**/*.json"]),
    edition = "2024",
    version = "0.0.0",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "openshell_ocsf_test",
    crate = ":openshell_ocsf",
    deps = all_crate_deps(normal_dev = True),
)
